data:
  trainset: /root/multiASR/egs/micArray/s5/exp/train.json
  devset: /root/multiASR/egs/micArray/s5/exp/test.json
  vocab_path: /root/multiASR/egs/micArray/s5/exp/aishell1_train_chars.txt
  maxlen: 60
  fetchworker_num: 6
  channels: 16
model:
  signal:
    feature_type: complex
    sample_rate: 16000
    num_mel_bins: 80
    use_energy: False
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    type: Transformer
    sub:
      type: ConvV2
      layer_num: 2
    input_dim: 257
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 6
    dropout_rate: 0.1
  decoder:
    type: TransformerDecoder
    vocab_size: -1 # derived by tokenizer
    d_model: 512
    nhead: 8
    num_layers: 6
    encoder_dim: 512
    dim_feedforward: 2048
    activation: "glu"
    dropout_rate: 0.1
training:
    batch_time: 150
    multi_gpu: True
    exp_dir: exp/multiASR
    print_inteval: 10
    num_epoch: 20
    accumulate_grad_batch: 8
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    lr_scheduler:
        type: "warmup_transformer"
        warmup_step: 16000
        d_model: 512
